### 流控测试
GET http://localhost:8000/flow


### 降级规则
GET http://localhost:8000/degrade

### 注解流控
GET http://localhost:8000/anno/flow

### 注解流控+降级
GET http://localhost:8000/anno/fallback?timeout=0


### 流控测试
GET http://localhost:8000/apollo/anno/flow