server:
  port: 31000

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    # 服务注册中心地址
    service-url:
      defaultZone: http://localhost:20000/eureka

eureka-client:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerRuleClassName: cn.mrcode.springcloud.rules.MyRule


