### 生产者消息发送
POST http://localhost:63000/send?body=Hellp Broadcast


### 生产者消息发送 - 分组消息
POST http://localhost:63000/send-to-group?body=Hellp Broadcast


### 生产者消息发送 - 分区
POST http://localhost:63000/send-to-group?body=1111
### 生产者消息发送 - 分区
POST http://localhost:63000/send-to-group?body=1


### 生产者消息发送 - 延迟消息
POST http://localhost:63000/send-to-delayed?body=1234580看&seconds=5


### 生产者消息发送 - 重试，不通过
POST http://localhost:63000/send-to-error?body=1234580

### 生产者消息发送 - 重试，重回队列
POST http://localhost:63000/send-to-requeue?body=1234580

### 生产者消息发送 - 死信队列测试
POST http://localhost:63000/send-to-dlq?body=1234580