server:
  port: 8001

spring:
  application:
    name: sentinel-apollo

# apollo 配置

## 应用 ID，对应的是 apollo 上的应用 ID
app.id: sentinel-apollo
## apollo 的 config-server 信息
apollo.meta: http://localhost:8080