server:
  port: 40001

spring:
  application:
    name: feign-consumer-advanced
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    # 服务注册中心地址
    service-url:
      defaultZone: http://localhost:20000/eureka


feign-client:
  ribbon:
    # 每台机器最大重试次数
    MaxAutoRetries: 2
    # 可以重试几台机器（第一台失败后，还可以换 2 台进行重试）
    MaxAutoRetriesNextServer: 2
    # 链接超时：http 请求会先链接，链接成功后，才会传递业务数据
    ConnectTimeout: 1000
    # 业务处理超时时间，没有响应数据的话
    ReadTimeout: 2000
    # 是否在所有的 HTTP METHOD 进行重试
    # 默认的话，仅在 get
    OkToRetryOnAllOperations: true