### 从网关发起调用
GET http://localhost:65000/FEIGN-CLIENT/sayHi

### 从网关发起调用
GET http://localhost:65000/feign-client/sayHi


### 获取路由信息
GET http://localhost:65000/actuator/gateway/routes

### 创建路由信息
POST http://localhost:65000/actuator/gateway/routes/dynamic
Content-Type: application/json

{
  "predicates": [
    {
      "name": "Path",
      "args": {
        "pattern": "/feign-client2/**"
      }
    }
  ],
  "filters": [
    {
      "name": "RewritePath",
      "args": {
        "regexp": "/feign-client2/(?<remaining>.*)",
        "replacement": "/${remaining}"
      }
    }
  ],
  "uri": "lb://FEIGN-CLIENT",
  "order": 0
}

### 测试动态路由添加的信息
GET http://localhost:65000/feign-client2/sayHi

### 删除路由信息
DELETE http://localhost:65000/actuator/gateway/routes/dynamic


### 从网关发起调用：yml 配置
GET http://localhost:65000/yml/sayHi

### 从网关发起调用：java 配置
GET http://localhost:65000/java/sayHi
name: xx


### =======  模拟秒杀业务
### 获取一个商品详情
GET http://localhost:65000/feign-client/gateway/details?pid=1

### 下单
POST http://localhost:65000/feign-client/gateway/placeOrder?pid=1

### 秒杀下单
POST http://localhost:65000/seckill/gateway/placeOrder?pid=1


### 自定义过滤器测试
GET http://localhost:65000/java/sayHi
name: xx

### 异常过滤器测试
GET http://localhost:65000/java/error2
name: xx

### 限流测试
GET http://localhost:65000/yml/sayHi
