server:
  port: 63000

spring:
  application:
    name: stream-sample
  # rabbit mq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        # 这里指定的是 channel 的名称
        myTopic-consumer:
          # 绑定到物理的 Exchange 名称
          destination: broadcast
        myTopic-producer:
          destination: broadcast

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always