### config-client:name
GET http://localhost:61000/name

### config-client:words
GET http://localhost:61000/words

### config-client:env
GET http://localhost:61000/env

### config-client: 动态刷新测试
GET http://localhost:61000/refres/words

### config-client: 访问刷新
POST http://localhost:61000/actuator/refresh

### config-server:
GET http://localhost:60000/main/config-consumer-dev.json


### config-client-eureka:name
GET http://localhost:61001/name

### config-client-eureka:words
GET http://localhost:61001/words

### 加密调用
GET http://localhost:60001/encrypt/status

### 加密调用
POST http://localhost:60001/encrypt

我是一个加密字符串

### 解密调用
POST http://localhost:60001/decrypt

719f419d00dc00d4837897301c5c01e9036a65287f0d75dc2a2320ee8b596944a3f9cc3c97ca9e1df3d9babc61aed043
